extends SceneTree
## Run: godot --headless --path . --script res://tests/test_group_model.gd
const Model = preload("res://addons/jigsawg/src/jigsaw_group_model.gd")
const Resolver = preload("res://addons/jigsawg/src/jigsaw_connection_resolver.gd")

func _initialize() -> void:
	var graph := Model.new()
	graph.reset(9)
	assert(graph.piece_count() == 9 and graph.group_count() == 9)
	assert(graph.root_of(-1) == -1 and graph.root_of(9) == -1)
	assert(not graph.same_group(0, 1))
	assert(graph.merge(0, 1) == PackedInt32Array([1]))
	assert(graph.merge(2, 3) == PackedInt32Array([3]))
	assert(graph.merge(0, 2) == PackedInt32Array([2, 3]))
	assert(graph.group_count() == 6)
	assert(graph.members_for(3) == PackedInt32Array([0, 1, 2, 3]))
	assert(graph.merge(1, 3).is_empty())
	var ids := graph.group_ids()
	assert(ids == PackedInt32Array([0, 0, 0, 0, 4, 5, 6, 7, 8]))
	var outside := graph.members_for(0)
	outside.append(8)
	assert(graph.members_for(0).size() == 4)

	assert(not graph.restore(PackedInt32Array([1, 2, 2])))
	assert(not graph.restore(PackedInt32Array([90, 1, 2])))
	assert(graph.group_ids() == ids, "Invalid restore cannot mutate current groups.")
	var other := Model.new()
	assert(other.restore(ids))
	assert(other.merge(4, 0) == PackedInt32Array([0, 1, 2, 3]))
	assert(other.root_of(3) == 4, "Anchor root must win union.")
	assert(other.group_count() == 5)
	graph.reset(4)
	assert(graph.group_count() == 4)
	graph.clear()
	assert(graph.piece_count() == 0 and graph.group_count() == 0)

	assert(Resolver.neighbor_ids(0, 3, 3) == PackedInt32Array([1, 3]))
	assert(Resolver.neighbor_ids(4, 3, 3) == PackedInt32Array([1, 5, 7, 3]))
	assert(Resolver.neighbor_ids(-1, 3, 3).is_empty())
	assert(Resolver.neighbor_ids(9, 3, 3).is_empty())
	var h0 := Vector2.ZERO
	var h1 := Vector2(100, 0)
	var offset := Resolver.snap_offset(h0, h1, Vector2(14, 20), Vector2(117, 20), 0, 0, 5.0)
	assert(offset.is_equal_approx(Vector2(3, 0)))
	assert(not Resolver.snap_offset(h0, h1, Vector2.ZERO, Vector2.ZERO, 0, 0, 5.0).is_finite())
	assert(not Resolver.snap_offset(h0, h1, Vector2.ZERO, Vector2(100, 0), 0, 1, 5.0).is_finite())
	assert(Resolver.snap_offset(h0, h1, Vector2.ZERO, Vector2(0, -100), 1, 1, 5.0).is_equal_approx(Vector2.ZERO))
	print("JigsawG group model and snap resolver: PASS")
	quit()
